version: "3"
services:
  mongo:
    image: mongo
    container_name: traco-mongo
    volumes:
      - ".docker-volumes/mongo/data:/data/db"
      - "./mongo-entrypoint:/docker-entrypoint-initdb.d"
    ports:
      - "27017:27017"
    env_file:
      - .env
  redis:
    image: redis
    container_name: traco-redis
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    env_file:
      - .env
  traco:
    depends_on:
      - mongo
      - redis
    build:
      context: "."
      dockerfile: "Dockerfile"
    image: traco
    container_name: traco
    ports:
      - "3000:3000"
    env_file:
      - .env